# Use root/example as user/password credentials
version: '3.3'

services:

  db:
    image: mysql:8
    volumes:
       - db_data:/var/lib/mysql
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: datamaker

  service:
    image: datamaker:1.0.5
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/datamaker
    ports:
      - 8080:8080

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

volumes:
    db_data: {}

